resolver: lts-18.18

packages:
- '.'

extra-deps:
  - git: 'https://github.com/RaitoBezarius/msgpack-haskell'
    commit: 58fad1691b8d8105238b2febdd86f15377385fcc
    subdirs:
      - msgpack

  - registry-0.2.1.0
  - registry-hedgehog-0.6.0.0

flags: {}

extra-package-dbs: []
