resolver: lts-19.10

packages:
- '.'

extra-deps:
  - protolude-0.3.1
  - git: 'https://github.com/RaitoBezarius/msgpack-haskell'
    commit: 58fad1691b8d8105238b2febdd86f15377385fcc
    subdirs:
      - msgpack

  - registry-0.3.0.7
  - registry-hedgehog-0.7.0.1

flags: {}

extra-package-dbs: []
