resolver: nightly-2022-09-29

packages:
- '.'

extra-deps:
  - int-cast-0.2.0.0
  - git: 'https://github.com/RaitoBezarius/msgpack-haskell'
    commit: 58fad1691b8d8105238b2febdd86f15377385fcc
    subdirs:
      - msgpack

flags: {}

extra-package-dbs: []
